---
- name: Config ELK VM with Docker
  hosts: elk
  remote_user: azadmin
  become: true
  tasks:
  
  - name: Use more memory
    sysctl:
      name: vm.max_map_count
      value: '262144'
      reload: yes
      
    - name: Install docker.io
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present
        
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present
        
    - name: Install docker python module
      pip:
        name: docker
        state: present
        
    - name: download and launch a docker web container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        # Ports that ELK runs on
        published_ports:
          - "5601:5601"
          - "9200:9200"
          - "5044:5044"

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes